//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class additionalServices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public additionalServices()
        {
            this.enableAdditionalServices = new HashSet<enableAdditionalServices>();
        }
    
        public int idAdditionalService { get; set; }
        public int idTariffs { get; set; }
        public int minutesPrice { get; set; }
        public int smsPrice { get; set; }
        public int gbPrice { get; set; }
    
        public virtual tariffs tariffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enableAdditionalServices> enableAdditionalServices { get; set; }
    }
}
