//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class enableAdditionalServices
    {
        public int idEnableAdditionService { get; set; }
        public int idEnableTariff { get; set; }
        public int idAdditionalService { get; set; }
        public int count { get; set; }
    
        public virtual additionalServices additionalServices { get; set; }
        public virtual enableTariffs enableTariffs { get; set; }
    }
}
