//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class enableTariffs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enableTariffs()
        {
            this.enableAdditionalServices = new HashSet<enableAdditionalServices>();
        }
    
        public int idEnableTariff { get; set; }
        public int idClientPhone { get; set; }
        public int idTariff { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual clientPhones clientPhones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enableAdditionalServices> enableAdditionalServices { get; set; }
        public virtual tariffs tariffs { get; set; }
    }
}
