//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cellServiceEntities : DbContext
    {
        public cellServiceEntities()
            : base("name=cellServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<additionalServices> additionalServices { get; set; }
        public virtual DbSet<clientPhones> clientPhones { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<enableAdditionalServices> enableAdditionalServices { get; set; }
        public virtual DbSet<enableTariffs> enableTariffs { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tariffs> tariffs { get; set; }
        public virtual DbSet<types> types { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
    }
}
