//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public string name { get; set; }
        public Nullable<int> idTariffs { get; set; }
        public Nullable<int> minutesPrice { get; set; }
        public Nullable<int> smsPrice { get; set; }
        public Nullable<int> gbPrice { get; set; }
        public int minutes { get; set; }
        public int gb { get; set; }
        public int sms { get; set; }
        public decimal price { get; set; }
    }
}
